name: Docker Build

on:
  push:
  create:
  workflow_dispatch:

permissions:
  packages: write

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}

    - name: Generate Docker tags
      uses: docker/metadata-action@v5
      id: metadata
      with:
        images: |
          ghcr.io/aibooruorg/prompt_protector
        tags: |
          type=sha,format=long,prefix=
          type=ref,event=branch
          type=ref,event=tag
          type=ref,event=pr
        # Tag `latest` on every commit pushed to master
        # https://github.com/docker/metadata-action/issues/112
        flavor: |
          latest=${{ github.ref == 'refs/heads/master' }}

    - name: Build image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}

        platforms: linux/amd64

        # https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#registry-cache
        # https://dev.to/pst418/speed-up-multi-stage-docker-builds-in-ci-cd-with-buildkit-s-registry-cache-11gi
        cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache
        cache-to: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache,mode=max

        build-args: |
          DOCKER_IMAGE_REVISION=${{ github.sha }}
          DOCKER_IMAGE_BUILD_DATE=${{ fromJSON(steps.metadata.outputs.json).labels['org.opencontainers.image.created'] }}

  deploy-production:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: docker-build
    concurrency: deploy-production

    environment:
      name: production
      url: https://prompt-protector.aibooru.online

    steps:
    - name: Install Kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: v1.21.5

    - name: Configure Kubectl
      run: |
        mkdir -p ~/.kube
        echo "$KUBECONFIG_YAML" > ~/.kube/config
      env:
        KUBECONFIG_YAML: ${{secrets.KUBECONFIG_YAML}}

    - name: Deploy to Production
      run: |
        kubectl rollout restart deploy/prompt-protector -n danbooru
